#!/usr/bin/env python3

import argparse
import requests
import uuid
import sys

def ussd(url, data):
    return requests.post(url, data)

def clean(ussdCode):
    return ussdCode.lstrip('*').rstrip('#')

def stop(responseText):
    cmd = responseText[0:4]
    return cmd == 'END '

if __name__ == "__main__":

    session_id = str(uuid.uuid4());

    parser = argparse.ArgumentParser(add_help=False, formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument('--api_uri', help="API URI", type=str, default="http://localhost:8000/api", metavar='')
    parser.add_argument('--number', help="Phone number", type=str, default="+256772100104", metavar='')
    parser.add_argument('--network_code', help="Network code", type=str, default="6001", metavar='')
    parser.add_argument('--service_code', help="USSD shortcode", type=str, default="*308#", metavar='')
    parser.add_argument('--dail', help="User input", type=str, default="", metavar='')
    parser.add_argument('--session_id', help="Session ID", type=str, default=session_id, metavar='')
    parser.add_argument('--version', action='version', version='%(prog)s v1.0 by eibatrm', help="Show program's info")
    parser.add_argument('--help', action='help', default=argparse.SUPPRESS, help='Show usage')

    args = parser.parse_args()

    # ........................................................

    service_code = clean(args.service_code)

    dail = clean(args.dail)

    answers = clean(dail.replace(service_code, ''))

    data = {
        'sessionId': args.session_id,
        'networkCode': args.network_code,
        'phoneNumber': args.number,
        'input': dail,
        'serviceCode': service_code,
        'text': answers
    }

    response = ussd(args.api_uri, data)

    if stop(response.text):
        print("\n" + response.text[4:])
        sys.exit(0);

    answer = input(response.text[4:] + "\n")

    # ..................................

    while True:
        dail += "*" + answer

        data = {
            'sessionId': args.session_id,
            'networkCode': args.network_code,
            'phoneNumber': args.number,
            'input': dail,
            'serviceCode': service_code,
            'text': answer
        }

        response = ussd(args.api_uri, data)

        if stop(response.text):
            print("\n" + response.text[4:])
            break;

        answer = input("\n" + response.text[4:] + "\n")
